---
title: "433 HW2"
author: "Yayu Zhu"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    code_folding: show
    toc: yes
    toc_depth: 4  
    toc_float: True
    theme: united
    highlight: tango
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lmtest)
library(sandwich)
library(tidyr)
library(plm)
library(dplyr)
library(kableExtra)
```

```{r}
stocks100_EW <- read.csv("100stocks_EW.csv",header=T)
# head(stocks100_EW)

stocks100_VW <- read.csv("100stocks_VW.csv",header=T)
# head(stocks100_VW)

file1 <- read.csv("file1.csv",header=T)
# head(file1)

file2_VW <- read.csv("file2_VW.csv",header=T)
# head(file2_VW)

file2_VW_clean <- read.csv("file2_VW_clean.csv",header=T)
# head(file2_VW_clean)

file2_EW <- read.csv("file2_EW.csv",header=T)
# head(file2_EW)

file3_VW <- read.csv("file3_VW.csv",header=T)
# head(file3_VW)

file3_EW <- read.csv("file3_EW.csv",header=T)
# head(file3_EW)

file4_VW <- read.csv("file4_VW.csv",header=T)
# head(file4_VW)

file4_VW2 <- read.csv("file4_VW2.csv",header=T)
# head(file4_VW2)

file4_VW2_clean <- read.csv("file4_VW2_clean.csv",header=T)
# head(file4_VW2_clean)

file4_EW <- read.csv("file4_EW.csv",header=T)
# head(file4_EW)

file5_VW <- read.csv("file5_VW.csv",header=T)
# head(file5_VW)

file5_EW <- read.csv("file5_EW.csv",header=T)
# head(file5_EW)

file6_VW <- read.csv("file6_VW.csv",header=T)
# head(file6_VW)

file6_EW <- read.csv("file6_EW.csv",header=T)
# head(file6_EW)
```
# Q1
## Q1 (A)
```{r}
# Q1 (A)
# m1=lm(E1~1,data=file2_VW)
# coeftest(m1,vcov=NeweyWest(m1,lag=6))
# m2=lm(E2~1,data=file2_VW)
# coeftest(m2,vcov=NeweyWest(m2,lag=6))
# m3=lm(E3~1,data=file2_VW)
# coeftest(m3,vcov=NeweyWest(m3,lag=6))
# m4=lm(E4~1,data=file2_VW)
# coeftest(m4,vcov=NeweyWest(m4,lag=6))
# m5=lm(E5~1,data=file2_VW)
# coeftest(m5,vcov=NeweyWest(m5,lag=6))
# m6=lm(E6~1,data=file2_VW)
# coeftest(m6,vcov=NeweyWest(m6,lag=6))
# m7=lm(E7~1,data=file2_VW)
# coeftest(m7,vcov=NeweyWest(m7,lag=6))
# m8=lm(E8~1,data=file2_VW)
# coeftest(m8,vcov=NeweyWest(m8,lag=6))
# m9=lm(E9~1,data=file2_VW)
# coeftest(m9,vcov=NeweyWest(m9,lag=6))
# m10=lm(E10~1,data=file2_VW)
# coeftest(m10,vcov=NeweyWest(m10,lag=6))
# 
# diff10_1_size=lm(E10_1~1,data=file2_VW)
# coeftest(diff10_1_size,vcov=NeweyWest(diff10_1_size,lag=6))

#Get all column names to run regression on
depVarList = setdiff(colnames(file2_VW_clean), c("Date", "MRP", "RF"))

#Loop over them and create model for each
allModels = lapply(depVarList, function(x){
    lm(formula= paste0("`", x, "` ~ 1"), 
     data= file2_VW_clean ,na.action = na.omit)
  
})
cts <- lapply(allModels, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts) = depVarList
result1a=as.data.frame(do.call("rbind", cts)[, 1:3])
result1a$name=depVarList
result1a=result1a[, c(4,1,2,3)]
result1a%>%kbl(caption ="Size Decile Portfolios-Mean Excess Return") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```
## Q1 (B)
```{r}
# Q1 (B)
# mm1=lm(E1~1,data=file3_VW)
# coeftest(mm1,vcov=NeweyWest(mm1,lag=6))
# mm2=lm(E2~1,data=file3_VW)
# coeftest(mm2,vcov=NeweyWest(mm2,lag=6))
# mm3=lm(E3~1,data=file3_VW)
# coeftest(mm3,vcov=NeweyWest(mm3,lag=6))
# mm4=lm(E4~1,data=file3_VW)
# coeftest(mm4,vcov=NeweyWest(mm4,lag=6))
# mm5=lm(E5~1,data=file3_VW)
# coeftest(mm5,vcov=NeweyWest(mm5,lag=6))
# mm6=lm(E6~1,data=file3_VW)
# coeftest(mm6,vcov=NeweyWest(mm6,lag=6))
# mm7=lm(E7~1,data=file3_VW)
# coeftest(mm7,vcov=NeweyWest(mm7,lag=6))
# mm8=lm(E8~1,data=file3_VW)
# coeftest(mm8,vcov=NeweyWest(mm8,lag=6))
# mm9=lm(E9~1,data=file3_VW)
# coeftest(mm9,vcov=NeweyWest(mm9,lag=6))
# mm10=lm(E10~1,data=file3_VW)
# coeftest(mm10,vcov=NeweyWest(mm10,lag=6))
# 
# diff10_1_BM=lm(E10_1~1,data=file3_VW)
# coeftest(diff10_1_BM,vcov=NeweyWest(diff10_1_BM,lag=6))

#Loop over them and create model for each
allModels2 = lapply(depVarList, function(x){
    lm(formula= paste0("`", x, "` ~ 1"), 
     data= file3_VW ,na.action = na.omit)
  
})
cts2 <- lapply(allModels2, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts2) = depVarList
result1b=as.data.frame(do.call("rbind", cts2)[, 1:3])
result1b$name=depVarList
result1b=result1b[, c(4,1,2,3)]
result1b%>%kbl(caption ="Book-to-Market Decile Portfolios-Mean Excess Return" ) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) 


```

## Q1 (C)
```{r}
# Q1 (C)
# CAPM1=lm(E1~MRP,data=file2_VW)
# coeftest(CAPM1,vcov=NeweyWest(CAPM1,lag=6))
# CAPM2=lm(E2~MRP,data=file2_VW)
# coeftest(CAPM2,vcov=NeweyWest(CAPM2,lag=6))
# CAPM3=lm(E3~MRP,data=file2_VW)
# coeftest(CAPM3,vcov=NeweyWest(CAPM3,lag=6))
# CAPM4=lm(E4~MRP,data=file2_VW)
# coeftest(CAPM4,vcov=NeweyWest(CAPM4,lag=6))
# CAPM5=lm(E5~MRP,data=file2_VW)
# coeftest(CAPM5,vcov=NeweyWest(CAPM5,lag=6))
# CAPM6=lm(E6~MRP,data=file2_VW)
# coeftest(CAPM6,vcov=NeweyWest(CAPM6,lag=6))
# CAPM7=lm(E7~MRP,data=file2_VW)
# coeftest(CAPM7,vcov=NeweyWest(CAPM7,lag=6))
# CAPM8=lm(E8~MRP,data=file2_VW)
# coeftest(CAPM8,vcov=NeweyWest(CAPM8,lag=6))
# CAPM9=lm(E9~MRP,data=file2_VW)
# coeftest(CAPM9,vcov=NeweyWest(CAPM9,lag=6))
# CAPM10=lm(E10~MRP,data=file2_VW)
# coeftest(CAPM10,vcov=NeweyWest(CAPM10,lag=6))
# 
# diff10_1_size_CAPM=lm(E10_1~MRP,data=file2_VW)
# coeftest(diff10_1_size_CAPM,vcov=NeweyWest(diff10_1_size_CAPM,lag=6))

#Loop over them and create model for each
allModels3 = lapply(depVarList, function(x){
    lm(formula= paste0("`", x, "` ~ MRP"), 
     data= file2_VW ,na.action = na.omit)
  
})
cts3 <- lapply(allModels3, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
depVarList_2=append(depVarList,depVarList)
depVarList_2=depVarList_2[order(nchar(depVarList_2), depVarList_2)]
names(cts3) = depVarList
result1c=as.data.frame(do.call("rbind", cts3)[, 1:3])
result1c$name=depVarList_2
result1c=result1c[, c(4,1,2,3)]
result1c%>%kbl(caption ="Size Decile Portfolios-CAPM" ) %>%
  kable_material_dark()
```

# Q2
## Q2 (A)
```{r}
# Q2 (A)
#Loop over them and create model for each
var2a=c("E_S_HBM","E_B_LBM","E_SHBM_BLBM")
models2a = lapply(var2a, function(x){
    lm(formula= paste0("`", x, "` ~ 1"), 
     data= file4_VW ,na.action = na.omit)
  
})
cts2a <- lapply(models2a, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts2a) = var2a
result2a=as.data.frame(do.call("rbind", cts2a)[, 1:3])
result2a$name=var2a
result2a=result2a[, c(4,1,2,3)]
result2a%>%kbl(caption ="S/HBM and B/LBM using 5*5 bivariate sorts-Mean Excess Return" ) %>%
  kable_material_dark()

diffSH_BL_CAPM=lm(E_SHBM_BLBM~MRP,data=file4_VW)
cts2a_CAPM=coeftest(diffSH_BL_CAPM,vcov=NeweyWest(diffSH_BL_CAPM,lag=6))
result2a_CAPM=as.data.frame(cts2a_CAPM[, 1:3])
result2a_CAPM%>%kbl(caption ="Differences in CAPM alphas between S/HBM and B/LBM" ) %>%
  kable_material_dark()
```

## Q2 (B)
```{r}
# Q2 (B)

# Step 1:
trans=as.data.frame(t(file4_VW2))

#Get all column names to run regression on
HERE=read.csv("HERE.csv",header=T)
depVarList_55 = setdiff(colnames(HERE), c("SandBM", "Size", "BM"))
#Loop over them and create model for each
allModels4 = lapply(depVarList_55, function(x){
    lm(formula= paste0("`", x, "` ~ Size+BM"), 
     data= HERE ,na.action = na.omit)
  
})
cts4 <- lapply(allModels4, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts4) = depVarList_55
result2b=as.data.frame(do.call("rbind", cts4)[, 1:3])
result2b$name=depVarList_55
# write.csv(result2b,file="result2b.csv")
 
# lapply(cts4, `[`, 1, 1:3) # constant
# lapply(cts4, `[`, 2 , 1:3) # Size
# lapply(cts4, `[`, 3, 1:3) # BM

#result2b_edit=read.csv("result2b_edit.csv",header=T)
# head(result2b_edit)

#result2b_edit %>% group_by(Key) %>% summarise_at(vars(-c(Std..Error,t.value)), funs(mean(., na.rm=TRUE)))

# Step 2:
result2b_here=read.csv("result2b_here.csv",header=T)

#Get all column names to run regression on
depVarList3 = colnames(result2b_here)

#Loop over them and create model for each
allModels5 = lapply(depVarList3, function(x){
    lm(formula= paste0("`", x, "` ~ 1"), 
     data= result2b_here ,na.action = na.omit)
})
cts5 <- lapply(allModels5, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts5) = depVarList3
resultfinal2b=as.data.frame(do.call("rbind", cts5)[, 1:3])
resultfinal2b$name=depVarList3
resultfinal2b=resultfinal2b[, c(4,1,2,3)]
resultfinal2b%>%kbl(caption ="FM Results-Size and BM 5*5" ) %>%
  kable_material_dark()

# inprogress<-gather(file4_VW2,S_BM,value,E11:E55)
# head(inprogress)
# write.csv(inprogress,file="inprogress.csv")
```

```{r}
# file4_VWYYY <- read.csv("file4_VWYYY.csv",header=T)
# head(file4_VWYYY)
# fpmg <- pmg(value~Size+BM, file4_VWYYY, index=c("Date","S_BM")) ##Fama-MacBeth
# coeftest(fpmg)
```

## Q2 (C)
```{r}
# Q2 (C)
# Step 1:
trans2=as.data.frame(t(file5_VW))

#Get all column names to run regression on
trans2c=read.csv("trans2c.csv",header=T)
depVarList_10beta = setdiff(colnames(trans2c), c("Key", "Beta"))
#Loop over them and create model for each
allModels6 = lapply(depVarList_10beta, function(x){
    lm(formula= paste0("`", x, "` ~ Beta"), 
     data= trans2c ,na.action = na.omit)
  
})
cts6 <- lapply(allModels6, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts6) = depVarList_10beta
result2c=as.data.frame(do.call("rbind", cts6)[, 1:3])

# lapply(cts4, `[`, 1, 1:3) # constant
# lapply(cts4, `[`, 2 , 1:3) # Size
# lapply(cts4, `[`, 3, 1:3) # BM

#result2b_edit=read.csv("result2b_edit.csv",header=T)
# head(result2b_edit)

#result2b_edit %>% group_by(Key) %>% summarise_at(vars(-c(Std..Error,t.value)), funs(mean(., na.rm=TRUE)))

# Step 2:
result2c_here=read.csv("result2c_here.csv",header=T)

#Get all column names to run regression on
depVarList4 = colnames(result2c_here)

#Loop over them and create model for each
allModels7 = lapply(depVarList4, function(x){
    lm(formula= paste0("`", x, "` ~ 1"), 
     data= result2c_here ,na.action = na.omit)
  
})
cts7 <- lapply(allModels7, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts7) = depVarList4
resultfinal2c=as.data.frame(do.call("rbind", cts7)[, 1:3])
resultfinal2c$name=depVarList4
resultfinal2c=resultfinal2c[, c(4,1,2,3)]
resultfinal2c%>%kbl(caption ="FM Results-Beta 5*5" ) %>%
  kable_material_dark()
# Bad news for CAPM

# pmg FM check
# file5_VW2=read.csv("file5_VW2.csv",header=T)
# inprogress2<-gather(file5_VW2,S_BM,value,E1:E10)
# 
# inprogress2 <- read.csv("inprogress2.csv",header=T)
# head(inprogress2)
# fpmg2 <- pmg(value~Betavalue, inprogress2, index=c("Date","Beta")) ##Fama-MacBeth
# coeftest(fpmg2)
```


# Q3
## Q3 (A)
```{r}
# Q3 (A)
var3a = c("E_LOW","E_HIGH","E_HIGH_LOW")

#Loop over them and create model for each
models3a = lapply(var3a, function(x){
    lm(formula= paste0("`", x, "` ~ MRP"), 
     data= file6_VW ,na.action = na.omit)
})
cts3a <- lapply(models3a, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts3a) = var3a
var3a_2=append(var3a,var3a)
var3a_2=var3a_2[order(nchar(var3a_2), var3a_2)]
resultfinal3a=as.data.frame(do.call("rbind", cts3a)[, 1:3])
resultfinal3a$name=var3a_2
resultfinal3a=resultfinal3a[, c(4,1,2,3)]
resultfinal3a%>%kbl(caption ="OP H/L-CAPM" ) %>%
  kable_material_dark()

```

## Q3 (B)
```{r}
# Q3 (B)
var3a = c("E_LOW","E_HIGH","E_HIGH_LOW")

#Loop over them and create model for each
models3b = lapply(var3a, function(x){
    lm(formula= paste0("`", x, "` ~ MRP+SMB+HML"), 
     data= file6_VW ,na.action = na.omit)
})
cts3b <- lapply(models3b, function(x){coeftest(x,vcov=NeweyWest(x,lag=6))})
names(cts3b) = var3a
var3b_2=append(var3a,var3a)
var3b_2=append(var3b_2,var3a)
var3b_2=append(var3b_2,var3a)
var3b_2=var3b_2[order(nchar(var3b_2), var3b_2)]
resultfinal3b=as.data.frame(do.call("rbind", cts3b)[, 1:3])
resultfinal3b$name=var3b_2
resultfinal3b=resultfinal3b[, c(4,1,2,3)]
resultfinal3b%>%kbl(caption ="OP H/L-FF3" ) %>%
  kable_material_dark()

# FF3_OP_LOW_VW=lm(E_LOW~MRP+SMB+HML,data=file6_VW)
# coeftest(FF3_OP_LOW_VW,vcov=NeweyWest(FF3_OP_LOW_VW,lag=6))
# 
# FF3_OP_HIGH_VW=lm(E_HIGH~MRP+SMB+HML,data=file6_VW)
# coeftest(FF3_OP_HIGH_VW,vcov=NeweyWest(FF3_OP_HIGH_VW,lag=6))
# 
# FF3_OP_HIGH_LOW_VW=lm(E_HIGH_LOW~MRP+SMB+HML,data=file6_VW)
# coeftest(FF3_OP_HIGH_LOW_VW,vcov=NeweyWest(FF3_OP_HIGH_LOW_VW,lag=6))
```

# Q4
## Q4 (A)
```{r}
# Q4 (A)
# EW
CAPM_100_EW=lm(Excess~MRP,data=stocks100_EW)
coeftest(CAPM_100_EW,vcov=NeweyWest(CAPM_100_EW,lag=6))


# VW
CAPM_100_VW=lm(Excess~MRP,data=stocks100_VW)
coeftest(CAPM_100_VW,vcov=NeweyWest(CAPM_100_VW,lag=6))
```
## Q4 (B)
```{r}
# Q4 (B)
FF3_100_EW=lm(Excess~MRP+SMB+HML,data=stocks100_EW)
coeftest(FF3_100_EW,vcov=NeweyWest(FF3_100_EW,lag=6))

FF3_100_VW=lm(Excess~MRP+SMB+HML,data=stocks100_VW)
coeftest(FF3_100_VW,vcov=NeweyWest(FF3_100_VW,lag=6))
```


